## 错误与异常

### 概念对比

错误和异常是两个不同的概念

| 概念 | 说明                                         | 示例                                  |
| ---- | -------------------------------------------- | ------------------------------------- |
| 错误 | 可以预先知道的可能会出错的【已知，意料之中】 | 除数为0                               |
| 异常 | 不可预知的问题叫做异常【未知，意料之外】     | 访问了映射中一个不存在的key；数组越界 |

```go
strconv.Itoa() // go 认为Itoa这个函数不可能发生错误，只可能发生异常

strconv.Atoi() // go 认为Atoi这个函数内部会出现一些能够预知的错误（比如输入了不正确的字符串 abcd），所以返回了error
```

### 常见的异常

1. 空指针引用
2. 下标越界
3. 不应该出现的分支，比如default
4. 输入错误引起的函数错误

其他场景，我们使用错误处理

### 错误处理和异常处理是不同的

| 错误或异常 | 处理方式        |
| ---------- | --------------- |
| 错误处理   | err != nil      |
| 异常处理   | panic + recover |



## 自定义错误

通过使用 `errors.New` 自定义错误，返回一个 `error` 类型的值

```go
error.New("错误说明")
```

使用经验

* 如果失败原因只有一个，则返回 `bool` 类型
* 如果失败原因不止一个，则返回 `error` 类型

错误可以进行类型断言

```go
file, err := os.Open("abc.txt")

if err != nil {
    if pathError, ok := err.(*os.PathError); ok {
        fmt.Println(pathError.Err)
    } else {
        fmt.Println("unkonwn error", err)
    }
}
```



## 抛出异常

使用内置函数 `panic`，接收任意值作为参数，引发异常

流程：一直向上返回，执行每一层的defer，如果没有遇见recover，则程序退出

`panic` 可以在任何位置引发，但是 `recover` 只能在 `defer` 中调用

```go
panic("message") // 指定 panic 发生时显示的信息
```



## defer-panic-recover机制

### 机制说明

默认情况下，当发生异常`(panic)`后，程序就会崩溃

如果希望当发生 `panic` 后，可以捕捉到 `panic`，并进行处理，从而使程序不崩溃，则需要进行错误处理

`Go` 不支持传统的 `try-catch-finally`，而是使用 `defer-panic-recover`机制

### 流程

程序错误抛出一个 `panic`，然后在 `defer` 语句中通过 `recover` 函数捕获这个 `panic`并处理，从而避免程序崩溃

### 示例

```go
package main

import "fmt"

func main() {
  test()
  fmt.Println("尽管发生了 panic，程序还是继续执行了") 
}

func test() {
  defer func() {
    r := recover() // recover内置函数，可以捕获异常
      if err, ok := r.(error); ok {
          fmt.Println("err=", err)
      } else {
          panic(r)
      }
  }()
   
  panic("引发异常")
}
```

### 注意

1. `recover()`必须搭配`defer`使用
2. `defer`一定要在可能引发`panic`的语句之前定义（因为`panic` 比 `default` 优先级要高）
3. `recover()` 必须在函数内部使用

```go
defer func() {
  recover() // 有效
}()

defer recover() // 无效
```

### 协程中的异常处理

Go设计认为：协程中的异常要自己捕获处理